image: gcc:latest

stages:
  - build
  - test

build_application:
  stage: build
  script:
    - apt-get update && apt-get install -y cmake
    - cmake -G "Unix Makefiles" -S . -B build
    - cmake --build build
  artifacts:
    paths:
      - build/
  only:
    - main

test_application:
  stage: test
  script:
    - ./build/run_tests 
    # Assume the build process generates an executable named run_tests
  dependencies:
    - build_application
  only:
    - main